In [101]:
import pandas as pd
from qdrant_client import QdrantClient
from qdrant_client.models import VectorParams, Distance, PayloadSchemaType, PointStruct, MatchAny, FieldCondition, Filter, Prefetch, FusionQuery

import pandas as pd
import numpy as np
import openai
import json
import tiktoken
from dotenv import load_dotenv
import os
import voyageai

In [102]:
qdrant_client = QdrantClient(url="http://localhost:6333")
load_dotenv()
VOYAGE_API_KEY = os.environ.get("VOYAGE_API_KEY")
voyageai_client = voyageai.Client(api_key=VOYAGE_API_KEY)

In [10]:
dummy_vector = np.zeros(1024).tolist()

payload = qdrant_client.query_points(
        collection_name="Amazon-items-collection-01-hybrid-search",
        query=dummy_vector,
        using="voyage-3",
        limit=1000,
        with_payload=["parent_asin"],
        with_vectors=False
)

parent_asin_list = [item.payload['parent_asin'] for item in payload.points]
df_reviews = pd.read_json("/Users/pranjal/Desktop/projects/AI/data/Electronic_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)
df_review_sample = df_reviews[df_reviews['parent_asin'].isin(parent_asin_list)]

In [11]:
df_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5,As good as advertised,This product is as good as advertised. The cos...,[{'small_image_url': 'https://m.media-amazon.c...,B07TZJ1CMC,B08912RRG5,AHITBJSS7KYUBVZPX7M2WJCOIVKQ,2022-05-22 20:42:27.409,0,True
1,5,"CIYUPE Tablet Pillow Stand, Tablet Holder (grey)","CIYUPE Tablet Pillow Stand, Tablet Holder Dock...",[],B09V28Y3HH,B09V28Y3HH,AHOEIYJJHZ7ITX75BOFQYNXVVJQQ,2022-12-17 14:53:32.718,1,True
2,5,Looks and works Great,Very small and unimposing support. Looks and w...,[{'small_image_url': 'https://m.media-amazon.c...,B0B2WCTGFV,B0B8N1CQD1,AEVPPTMG43C6GWSR7I2UGRQN7WFQ,2023-02-02 16:42:57.140,0,True
3,5,Didn't work with Motorola 5g uw,I read all directions and charged up my earbud...,[],B092M34HQ3,B0C2BVCBRV,AGSMNIT5YGSO35M2YRIE2OZIOSUQ,2022-05-12 01:30:34.627,0,True
4,5,Two Position Holder,"Durable, has two sturdy positions for iPad and...",[],B09WMLKQ8D,B09HKP7N83,AFJHM4DEMY7IU6ZCUBCETLREE43Q,2022-11-10 19:08:51.479,0,True

# Now we will preprocess the data
We will now compute the title + text
but we have to make sure that this title + text length is less then the max tokens our embedding model can embed
Right now voyage-3 can embed 32k tokens with total of 128 text array in one api calls

In [94]:
# Define functions to preprocess reviews data

def preprocess_reviews_data(row):
    return f"{row['title']} {row['text']}"

# this is exact token count as per voyage-3, since tiktoken oonly do for openai models
# we use the cl100k_base, which is good aprox for voyage-3 
# what we want to achieve here is we want aprox token count per title+text and then use only title+text where len(title+text) < max text length the model can embed
# in our case its voyage-3 which has 32k max length of text length, therefore this does not apply to us
# here we have 2 methods for count of tokens in the title+text
def token_count(row):
        encoding = tiktoken.get_encoding("cl100k_base")
        return len(encoding.encode(row["preprocessed_data"]))

def approx_token_count(row):
        return int(len(row["preprocessed_data"].split()) * 1.2)

df_review_sample["preprocessed_data"] = df_review_sample.apply(preprocess_reviews_data, axis=1)
df_review_sample["preprocessed_data_token_count"] = df_review_sample.apply(token_count, axis=1)
df_review_sample["preprocessed_data_approx_token_count"] = df_review_sample.apply(approx_token_count, axis=1)
# df_review_sample = df_review_sample[df_review_sample["preprocessed_data_token_count"] < 32000]
df_review_sample = df_review_sample[df_review_sample["preprocessed_data_approx_token_count"] < 32000]

In [95]:
df_review_sample.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,preprocessed_data,preprocessed_data_token_count,preprocessed_data_approx_token_count
0,5,As good as advertised,This product is as good as advertised. The cos...,[{'small_image_url': 'https://m.media-amazon.c...,B07TZJ1CMC,B08912RRG5,AHITBJSS7KYUBVZPX7M2WJCOIVKQ,2022-05-22 20:42:27.409,0,True,As good as advertised This product is as good ...,43,45
1,5,"CIYUPE Tablet Pillow Stand, Tablet Holder (grey)","CIYUPE Tablet Pillow Stand, Tablet Holder Dock...",[],B09V28Y3HH,B09V28Y3HH,AHOEIYJJHZ7ITX75BOFQYNXVVJQQ,2022-12-17 14:53:32.718,1,True,"CIYUPE Tablet Pillow Stand, Tablet Holder (gre...",104,78
2,5,Looks and works Great,Very small and unimposing support. Looks and w...,[{'small_image_url': 'https://m.media-amazon.c...,B0B2WCTGFV,B0B8N1CQD1,AEVPPTMG43C6GWSR7I2UGRQN7WFQ,2023-02-02 16:42:57.140,0,True,Looks and works Great Very small and unimposin...,17,15
3,5,Didn't work with Motorola 5g uw,I read all directions and charged up my earbud...,[],B092M34HQ3,B0C2BVCBRV,AGSMNIT5YGSO35M2YRIE2OZIOSUQ,2022-05-12 01:30:34.627,0,True,Didn't work with Motorola 5g uw I read all dir...,40,36
4,5,Two Position Holder,"Durable, has two sturdy positions for iPad and...",[],B09WMLKQ8D,B09HKP7N83,AFJHM4DEMY7IU6ZCUBCETLREE43Q,2022-11-10 19:08:51.479,0,True,"Two Position Holder Durable, has two sturdy po...",18,18

In [97]:
total_tokens = df_review_sample["preprocessed_data_approx_token_count"].sum()
total_tokens

np.int64(5274020)

### Create new Qdrant for reviews

In [98]:
qdrant_client.create_collection(
        collection_name="Amazon-items-collection-01-reviews",
        vectors_config=VectorParams(size=1024, distance=Distance.COSINE)
)

True

In [99]:
qdrant_client.create_payload_index(
        collection_name="Amazon-items-collection-01-reviews",
        field_name="parent_asin",                 # we will be running many queries
        field_schema=PayloadSchemaType.KEYWORD,   # This will be an exact match
)

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

In [103]:
def get_embedding(text, model='voyage-3'):
        result = voyageai_client.embed(
                [text],
                model=model,
        )
        return result.embeddings[0]

def get_embedding_batch(text_list, model='voyage-3', batch_size=100):
        embeddings = []
        counter=1
        for i in range(0, len(text_list), batch_size):
                batch = text_list[i:i + batch_size]
                result = voyageai_client.embed(batch, model=model)
                embeddings.extend(result.embeddings)
                print(f"Processed {counter * batch_size} of {len(text_list)}")
                counter += 1
        return embeddings

### Embed the title+text

In [104]:
data_to_embed_reviews = df_review_sample[['preprocessed_data', 'parent_asin']].to_dict(orient='records')
text_to_embed_reviews = [data['preprocessed_data'] for data in data_to_embed_reviews]
embeddings_reviews = get_embedding_batch(text_to_embed_reviews)

Processed 100 of 91450
Processed 200 of 91450
Processed 300 of 91450
Processed 400 of 91450
Processed 500 of 91450
Processed 600 of 91450
Processed 700 of 91450
Processed 800 of 91450
Processed 900 of 91450
Processed 1000 of 91450
Processed 1100 of 91450
Processed 1200 of 91450
Processed 1300 of 91450
Processed 1400 of 91450
Processed 1500 of 91450
Processed 1600 of 91450
Processed 1700 of 91450
Processed 1800 of 91450
Processed 1900 of 91450
Processed 2000 of 91450
Processed 2100 of 91450
Processed 2200 of 91450
Processed 2300 of 91450
Processed 2400 of 91450
Processed 2500 of 91450
Processed 2600 of 91450
Processed 2700 of 91450
Processed 2800 of 91450
Processed 2900 of 91450
Processed 3000 of 91450
Processed 3100 of 91450
Processed 3200 of 91450
Processed 3300 of 91450
Processed 3400 of 91450
Processed 3500 of 91450
Processed 3600 of 91450
Processed 3700 of 91450
Processed 3800 of 91450
Processed 3900 of 91450
Processed 4000 of 91450
Processed 4100 of 91450
Processed 4200 of 91450
Processed 4300 of 91450
Processed 4400 of 91450
Processed 4500 of 91450
Processed 4600 of 91450
Processed 4700 of 91450
Processed 4800 of 91450
Processed 4900 of 91450
Processed 5000 of 91450
Processed 5100 of 91450
Processed 5200 of 91450
Processed 5300 of 91450
Processed 5400 of 91450
Processed 5500 of 91450
Processed 5600 of 91450
Processed 5700 of 91450
Processed 5800 of 91450
Processed 5900 of 91450
Processed 6000 of 91450
Processed 6100 of 91450
Processed 6200 of 91450
Processed 6300 of 91450
Processed 6400 of 91450
Processed 6500 of 91450
Processed 6600 of 91450
Processed 6700 of 91450
Processed 6800 of 91450
Processed 6900 of 91450
Processed 7000 of 91450
Processed 7100 of 91450
Processed 7200 of 91450
Processed 7300 of 91450
Processed 7400 of 91450
Processed 7500 of 91450
Processed 7600 of 91450
Processed 7700 of 91450
Processed 7800 of 91450
Processed 7900 of 91450
Processed 8000 of 91450
Processed 8100 of 91450
Processed 8200 of 91450
Processed 8300 of 91450
Processed 8400 of 91450
Processed 8500 of 91450
Processed 8600 of 91450
Processed 8700 of 91450
Processed 8800 of 91450
Processed 8900 of 91450
Processed 9000 of 91450
Processed 9100 of 91450
Processed 9200 of 91450
Processed 9300 of 91450
Processed 9400 of 91450
Processed 9500 of 91450
Processed 9600 of 91450
Processed 9700 of 91450
Processed 9800 of 91450
Processed 9900 of 91450
Processed 10000 of 91450
Processed 10100 of 91450
Processed 10200 of 91450
Processed 10300 of 91450
Processed 10400 of 91450
Processed 10500 of 91450
Processed 10600 of 91450
Processed 10700 of 91450
Processed 10800 of 91450
Processed 10900 of 91450
Processed 11000 of 91450
Processed 11100 of 91450
Processed 11200 of 91450
Processed 11300 of 91450
Processed 11400 of 91450
Processed 11500 of 91450
Processed 11600 of 91450
Processed 11700 of 91450
Processed 11800 of 91450
Processed 11900 of 91450
Processed 12000 of 91450
Processed 12100 of 91450
Processed 12200 of 91450
Processed 12300 of 91450
Processed 12400 of 91450
Processed 12500 of 91450
Processed 12600 of 91450
Processed 12700 of 91450
Processed 12800 of 91450
Processed 12900 of 91450
Processed 13000 of 91450
Processed 13100 of 91450
Processed 13200 of 91450
Processed 13300 of 91450
Processed 13400 of 91450
Processed 13500 of 91450
Processed 13600 of 91450
Processed 13700 of 91450
Processed 13800 of 91450
Processed 13900 of 91450
Processed 14000 of 91450
Processed 14100 of 91450
Processed 14200 of 91450
Processed 14300 of 91450
Processed 14400 of 91450
Processed 14500 of 91450
Processed 14600 of 91450
Processed 14700 of 91450
Processed 14800 of 91450
Processed 14900 of 91450
Processed 15000 of 91450
Processed 15100 of 91450
Processed 15200 of 91450
Processed 15300 of 91450
Processed 15400 of 91450
Processed 15500 of 91450
Processed 15600 of 91450
Processed 15700 of 91450
Processed 15800 of 91450
Processed 15900 of 91450
Processed 16000 of 91450
Processed 16100 of 91450
Processed 16200 of 91450
Processed 16300 of 91450
Processed 16400 of 91450
Processed 16500 of 91450
Processed 16600 of 91450
Processed 16700 of 91450
Processed 16800 of 91450
Processed 16900 of 91450
Processed 17000 of 91450
Processed 17100 of 91450
Processed 17200 of 91450
Processed 17300 of 91450
Processed 17400 of 91450
Processed 17500 of 91450
Processed 17600 of 91450
Processed 17700 of 91450
Processed 17800 of 91450
Processed 17900 of 91450
Processed 18000 of 91450
Processed 18100 of 91450
Processed 18200 of 91450
Processed 18300 of 91450
Processed 18400 of 91450
Processed 18500 of 91450
Processed 18600 of 91450
Processed 18700 of 91450
Processed 18800 of 91450
Processed 18900 of 91450
Processed 19000 of 91450
Processed 19100 of 91450
Processed 19200 of 91450
Processed 19300 of 91450
Processed 19400 of 91450
Processed 19500 of 91450
Processed 19600 of 91450
Processed 19700 of 91450
Processed 19800 of 91450
Processed 19900 of 91450
Processed 20000 of 91450
Processed 20100 of 91450
Processed 20200 of 91450
Processed 20300 of 91450
Processed 20400 of 91450
Processed 20500 of 91450
Processed 20600 of 91450
Processed 20700 of 91450
Processed 20800 of 91450
Processed 20900 of 91450
Processed 21000 of 91450
Processed 21100 of 91450
Processed 21200 of 91450
Processed 21300 of 91450
Processed 21400 of 91450
Processed 21500 of 91450
Processed 21600 of 91450
Processed 21700 of 91450
Processed 21800 of 91450
Processed 21900 of 91450
Processed 22000 of 91450
Processed 22100 of 91450
Processed 22200 of 91450
Processed 22300 of 91450
Processed 22400 of 91450
Processed 22500 of 91450
Processed 22600 of 91450
Processed 22700 of 91450
Processed 22800 of 91450
Processed 22900 of 91450
Processed 23000 of 91450
Processed 23100 of 91450
Processed 23200 of 91450
Processed 23300 of 91450
Processed 23400 of 91450
Processed 23500 of 91450
Processed 23600 of 91450
Processed 23700 of 91450
Processed 23800 of 91450
Processed 23900 of 91450
Processed 24000 of 91450
Processed 24100 of 91450
Processed 24200 of 91450
Processed 24300 of 91450
Processed 24400 of 91450
Processed 24500 of 91450
Processed 24600 of 91450
Processed 24700 of 91450
Processed 24800 of 91450
Processed 24900 of 91450
Processed 25000 of 91450
Processed 25100 of 91450
Processed 25200 of 91450
Processed 25300 of 91450
Processed 25400 of 91450
Processed 25500 of 91450
Processed 25600 of 91450
Processed 25700 of 91450
Processed 25800 of 91450
Processed 25900 of 91450
Processed 26000 of 91450
Processed 26100 of 91450
Processed 26200 of 91450
Processed 26300 of 91450
Processed 26400 of 91450
Processed 26500 of 91450
Processed 26600 of 91450
Processed 26700 of 91450
Processed 26800 of 91450
Processed 26900 of 91450
Processed 27000 of 91450
Processed 27100 of 91450
Processed 27200 of 91450
Processed 27300 of 91450
Processed 27400 of 91450
Processed 27500 of 91450
Processed 27600 of 91450
Processed 27700 of 91450
Processed 27800 of 91450
Processed 27900 of 91450
Processed 28000 of 91450
Processed 28100 of 91450
Processed 28200 of 91450
Processed 28300 of 91450
Processed 28400 of 91450
Processed 28500 of 91450
Processed 28600 of 91450
Processed 28700 of 91450
Processed 28800 of 91450
Processed 28900 of 91450
Processed 29000 of 91450
Processed 29100 of 91450
Processed 29200 of 91450
Processed 29300 of 91450
Processed 29400 of 91450
Processed 29500 of 91450
Processed 29600 of 91450
Processed 29700 of 91450
Processed 29800 of 91450
Processed 29900 of 91450
Processed 30000 of 91450
Processed 30100 of 91450
Processed 30200 of 91450
Processed 30300 of 91450
Processed 30400 of 91450
Processed 30500 of 91450
Processed 30600 of 91450
Processed 30700 of 91450
Processed 30800 of 91450
Processed 30900 of 91450
Processed 31000 of 91450
Processed 31100 of 91450
Processed 31200 of 91450
Processed 31300 of 91450
Processed 31400 of 91450
Processed 31500 of 91450
Processed 31600 of 91450
Processed 31700 of 91450
Processed 31800 of 91450
Processed 31900 of 91450
Processed 32000 of 91450
Processed 32100 of 91450
Processed 32200 of 91450
Processed 32300 of 91450
Processed 32400 of 91450
Processed 32500 of 91450
Processed 32600 of 91450
Processed 32700 of 91450
Processed 32800 of 91450
Processed 32900 of 91450
Processed 33000 of 91450
Processed 33100 of 91450
Processed 33200 of 91450
Processed 33300 of 91450
Processed 33400 of 91450
Processed 33500 of 91450
Processed 33600 of 91450
Processed 33700 of 91450
Processed 33800 of 91450
Processed 33900 of 91450
Processed 34000 of 91450
Processed 34100 of 91450
Processed 34200 of 91450
Processed 34300 of 91450
Processed 34400 of 91450
Processed 34500 of 91450
Processed 34600 of 91450
Processed 34700 of 91450
Processed 34800 of 91450
Processed 34900 of 91450
Processed 35000 of 91450
Processed 35100 of 91450
Processed 35200 of 91450
Processed 35300 of 91450
Processed 35400 of 91450
Processed 35500 of 91450
Processed 35600 of 91450
Processed 35700 of 91450
Processed 35800 of 91450
Processed 35900 of 91450
Processed 36000 of 91450
Processed 36100 of 91450
Processed 36200 of 91450
Processed 36300 of 91450
Processed 36400 of 91450
Processed 36500 of 91450
Processed 36600 of 91450
Processed 36700 of 91450
Processed 36800 of 91450
Processed 36900 of 91450
Processed 37000 of 91450
Processed 37100 of 91450
Processed 37200 of 91450
Processed 37300 of 91450
Processed 37400 of 91450
Processed 37500 of 91450
Processed 37600 of 91450
Processed 37700 of 91450
Processed 37800 of 91450
Processed 37900 of 91450
Processed 38000 of 91450
Processed 38100 of 91450
Processed 38200 of 91450
Processed 38300 of 91450
Processed 38400 of 91450
Processed 38500 of 91450
Processed 38600 of 91450
Processed 38700 of 91450
Processed 38800 of 91450
Processed 38900 of 91450
Processed 39000 of 91450
Processed 39100 of 91450
Processed 39200 of 91450
Processed 39300 of 91450
Processed 39400 of 91450
Processed 39500 of 91450
Processed 39600 of 91450
Processed 39700 of 91450
Processed 39800 of 91450
Processed 39900 of 91450
Processed 40000 of 91450
Processed 40100 of 91450
Processed 40200 of 91450
Processed 40300 of 91450
Processed 40400 of 91450
Processed 40500 of 91450
Processed 40600 of 91450
Processed 40700 of 91450
Processed 40800 of 91450
Processed 40900 of 91450
Processed 41000 of 91450
Processed 41100 of 91450
Processed 41200 of 91450
Processed 41300 of 91450
Processed 41400 of 91450
Processed 41500 of 91450
Processed 41600 of 91450
Processed 41700 of 91450
Processed 41800 of 91450
Processed 41900 of 91450
Processed 42000 of 91450
Processed 42100 of 91450
Processed 42200 of 91450
Processed 42300 of 91450
Processed 42400 of 91450
Processed 42500 of 91450
Processed 42600 of 91450
Processed 42700 of 91450
Processed 42800 of 91450
Processed 42900 of 91450
Processed 43000 of 91450
Processed 43100 of 91450
Processed 43200 of 91450
Processed 43300 of 91450
Processed 43400 of 91450
Processed 43500 of 91450
Processed 43600 of 91450
Processed 43700 of 91450
Processed 43800 of 91450
Processed 43900 of 91450
Processed 44000 of 91450
Processed 44100 of 91450
Processed 44200 of 91450
Processed 44300 of 91450
Processed 44400 of 91450
Processed 44500 of 91450
Processed 44600 of 91450
Processed 44700 of 91450
Processed 44800 of 91450
Processed 44900 of 91450
Processed 45000 of 91450
Processed 45100 of 91450
Processed 45200 of 91450
Processed 45300 of 91450
Processed 45400 of 91450
Processed 45500 of 91450
Processed 45600 of 91450
Processed 45700 of 91450
Processed 45800 of 91450
Processed 45900 of 91450
Processed 46000 of 91450
Processed 46100 of 91450
Processed 46200 of 91450
Processed 46300 of 91450
Processed 46400 of 91450
Processed 46500 of 91450
Processed 46600 of 91450
Processed 46700 of 91450
Processed 46800 of 91450
Processed 46900 of 91450
Processed 47000 of 91450
Processed 47100 of 91450
Processed 47200 of 91450
Processed 47300 of 91450
Processed 47400 of 91450
Processed 47500 of 91450
Processed 47600 of 91450
Processed 47700 of 91450
Processed 47800 of 91450
Processed 47900 of 91450
Processed 48000 of 91450
Processed 48100 of 91450
Processed 48200 of 91450
Processed 48300 of 91450
Processed 48400 of 91450
Processed 48500 of 91450
Processed 48600 of 91450
Processed 48700 of 91450
Processed 48800 of 91450
Processed 48900 of 91450
Processed 49000 of 91450
Processed 49100 of 91450
Processed 49200 of 91450
Processed 49300 of 91450
Processed 49400 of 91450
Processed 49500 of 91450
Processed 49600 of 91450
Processed 49700 of 91450
Processed 49800 of 91450
Processed 49900 of 91450
Processed 50000 of 91450
Processed 50100 of 91450
Processed 50200 of 91450
Processed 50300 of 91450
Processed 50400 of 91450
Processed 50500 of 91450
Processed 50600 of 91450
Processed 50700 of 91450
Processed 50800 of 91450
Processed 50900 of 91450
Processed 51000 of 91450
Processed 51100 of 91450
Processed 51200 of 91450
Processed 51300 of 91450
Processed 51400 of 91450
Processed 51500 of 91450
Processed 51600 of 91450
Processed 51700 of 91450
Processed 51800 of 91450
Processed 51900 of 91450
Processed 52000 of 91450
Processed 52100 of 91450
Processed 52200 of 91450
Processed 52300 of 91450
Processed 52400 of 91450
Processed 52500 of 91450
Processed 52600 of 91450
Processed 52700 of 91450
Processed 52800 of 91450
Processed 52900 of 91450
Processed 53000 of 91450
Processed 53100 of 91450
Processed 53200 of 91450
Processed 53300 of 91450
Processed 53400 of 91450
Processed 53500 of 91450
Processed 53600 of 91450
Processed 53700 of 91450
Processed 53800 of 91450
Processed 53900 of 91450
Processed 54000 of 91450
Processed 54100 of 91450
Processed 54200 of 91450
Processed 54300 of 91450
Processed 54400 of 91450
Processed 54500 of 91450
Processed 54600 of 91450
Processed 54700 of 91450
Processed 54800 of 91450
Processed 54900 of 91450
Processed 55000 of 91450
Processed 55100 of 91450
Processed 55200 of 91450
Processed 55300 of 91450
Processed 55400 of 91450
Processed 55500 of 91450
Processed 55600 of 91450
Processed 55700 of 91450
Processed 55800 of 91450
Processed 55900 of 91450
Processed 56000 of 91450
Processed 56100 of 91450
Processed 56200 of 91450
Processed 56300 of 91450
Processed 56400 of 91450
Processed 56500 of 91450
Processed 56600 of 91450
Processed 56700 of 91450
Processed 56800 of 91450
Processed 56900 of 91450
Processed 57000 of 91450
Processed 57100 of 91450
Processed 57200 of 91450
Processed 57300 of 91450
Processed 57400 of 91450
Processed 57500 of 91450
Processed 57600 of 91450
Processed 57700 of 91450
Processed 57800 of 91450
Processed 57900 of 91450
Processed 58000 of 91450
Processed 58100 of 91450
Processed 58200 of 91450
Processed 58300 of 91450
Processed 58400 of 91450
Processed 58500 of 91450
Processed 58600 of 91450
Processed 58700 of 91450
Processed 58800 of 91450
Processed 58900 of 91450
Processed 59000 of 91450
Processed 59100 of 91450
Processed 59200 of 91450
Processed 59300 of 91450
Processed 59400 of 91450
Processed 59500 of 91450
Processed 59600 of 91450
Processed 59700 of 91450
Processed 59800 of 91450
Processed 59900 of 91450
Processed 60000 of 91450
Processed 60100 of 91450
Processed 60200 of 91450
Processed 60300 of 91450
Processed 60400 of 91450
Processed 60500 of 91450
Processed 60600 of 91450
Processed 60700 of 91450
Processed 60800 of 91450
Processed 60900 of 91450
Processed 61000 of 91450
Processed 61100 of 91450
Processed 61200 of 91450
Processed 61300 of 91450
Processed 61400 of 91450
Processed 61500 of 91450
Processed 61600 of 91450
Processed 61700 of 91450
Processed 61800 of 91450
Processed 61900 of 91450
Processed 62000 of 91450
Processed 62100 of 91450
Processed 62200 of 91450
Processed 62300 of 91450
Processed 62400 of 91450
Processed 62500 of 91450
Processed 62600 of 91450
Processed 62700 of 91450
Processed 62800 of 91450
Processed 62900 of 91450
Processed 63000 of 91450
Processed 63100 of 91450
Processed 63200 of 91450
Processed 63300 of 91450
Processed 63400 of 91450
Processed 63500 of 91450
Processed 63600 of 91450
Processed 63700 of 91450
Processed 63800 of 91450
Processed 63900 of 91450
Processed 64000 of 91450
Processed 64100 of 91450
Processed 64200 of 91450
Processed 64300 of 91450
Processed 64400 of 91450
Processed 64500 of 91450
Processed 64600 of 91450
Processed 64700 of 91450
Processed 64800 of 91450
Processed 64900 of 91450
Processed 65000 of 91450
Processed 65100 of 91450
Processed 65200 of 91450
Processed 65300 of 91450
Processed 65400 of 91450
Processed 65500 of 91450
Processed 65600 of 91450
Processed 65700 of 91450
Processed 65800 of 91450
Processed 65900 of 91450
Processed 66000 of 91450
Processed 66100 of 91450
Processed 66200 of 91450
Processed 66300 of 91450
Processed 66400 of 91450
Processed 66500 of 91450
Processed 66600 of 91450
Processed 66700 of 91450
Processed 66800 of 91450
Processed 66900 of 91450
Processed 67000 of 91450
Processed 67100 of 91450
Processed 67200 of 91450
Processed 67300 of 91450
Processed 67400 of 91450
Processed 67500 of 91450
Processed 67600 of 91450
Processed 67700 of 91450
Processed 67800 of 91450
Processed 67900 of 91450
Processed 68000 of 91450
Processed 68100 of 91450
Processed 68200 of 91450
Processed 68300 of 91450
Processed 68400 of 91450
Processed 68500 of 91450
Processed 68600 of 91450
Processed 68700 of 91450
Processed 68800 of 91450
Processed 68900 of 91450
Processed 69000 of 91450
Processed 69100 of 91450
Processed 69200 of 91450
Processed 69300 of 91450
Processed 69400 of 91450
Processed 69500 of 91450
Processed 69600 of 91450
Processed 69700 of 91450
Processed 69800 of 91450
Processed 69900 of 91450
Processed 70000 of 91450
Processed 70100 of 91450
Processed 70200 of 91450
Processed 70300 of 91450
Processed 70400 of 91450
Processed 70500 of 91450
Processed 70600 of 91450
Processed 70700 of 91450
Processed 70800 of 91450
Processed 70900 of 91450
Processed 71000 of 91450
Processed 71100 of 91450
Processed 71200 of 91450
Processed 71300 of 91450
Processed 71400 of 91450
Processed 71500 of 91450
Processed 71600 of 91450
Processed 71700 of 91450
Processed 71800 of 91450
Processed 71900 of 91450
Processed 72000 of 91450
Processed 72100 of 91450
Processed 72200 of 91450
Processed 72300 of 91450
Processed 72400 of 91450
Processed 72500 of 91450
Processed 72600 of 91450
Processed 72700 of 91450
Processed 72800 of 91450
Processed 72900 of 91450
Processed 73000 of 91450
Processed 73100 of 91450
Processed 73200 of 91450
Processed 73300 of 91450
Processed 73400 of 91450
Processed 73500 of 91450
Processed 73600 of 91450
Processed 73700 of 91450
Processed 73800 of 91450
Processed 73900 of 91450
Processed 74000 of 91450
Processed 74100 of 91450
Processed 74200 of 91450
Processed 74300 of 91450
Processed 74400 of 91450
Processed 74500 of 91450
Processed 74600 of 91450
Processed 74700 of 91450
Processed 74800 of 91450
Processed 74900 of 91450
Processed 75000 of 91450
Processed 75100 of 91450
Processed 75200 of 91450
Processed 75300 of 91450
Processed 75400 of 91450
Processed 75500 of 91450
Processed 75600 of 91450
Processed 75700 of 91450
Processed 75800 of 91450
Processed 75900 of 91450
Processed 76000 of 91450
Processed 76100 of 91450
Processed 76200 of 91450
Processed 76300 of 91450
Processed 76400 of 91450
Processed 76500 of 91450
Processed 76600 of 91450
Processed 76700 of 91450
Processed 76800 of 91450
Processed 76900 of 91450
Processed 77000 of 91450
Processed 77100 of 91450
Processed 77200 of 91450
Processed 77300 of 91450
Processed 77400 of 91450
Processed 77500 of 91450
Processed 77600 of 91450
Processed 77700 of 91450
Processed 77800 of 91450
Processed 77900 of 91450
Processed 78000 of 91450
Processed 78100 of 91450
Processed 78200 of 91450
Processed 78300 of 91450
Processed 78400 of 91450
Processed 78500 of 91450
Processed 78600 of 91450
Processed 78700 of 91450
Processed 78800 of 91450
Processed 78900 of 91450
Processed 79000 of 91450
Processed 79100 of 91450
Processed 79200 of 91450
Processed 79300 of 91450
Processed 79400 of 91450
Processed 79500 of 91450
Processed 79600 of 91450
Processed 79700 of 91450
Processed 79800 of 91450
Processed 79900 of 91450
Processed 80000 of 91450
Processed 80100 of 91450
Processed 80200 of 91450
Processed 80300 of 91450
Processed 80400 of 91450

In [105]:
pointstructs = []
i = 1
for embedding, data in zip(embeddings_reviews, data_to_embed_reviews):
        pointstructs.append(
                PointStruct(
                        id=i,
                        vector=embedding,
                        payload={
                                'text': data['preprocessed_data'],
                                'parent_asin': data['parent_asin']
                        }
                )
        )
        i += 1

In [106]:
# put the embedding in qdrant
counter = 1
for i in range(0, len(pointstructs), 100):
        batch = pointstructs[i: i+100]
        qdrant_client.upsert(
                collection_name='Amazon-items-collection-01-reviews',
                wait=True,
                points=batch,
        )
        print(f"Processed {counter*1000} of {len(pointstructs)}")

Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450
Processed 1000 of 91450

In [107]:
# function to run search for reviews on set of parent_asin
def retrieve_prefiltered_reviews_data(query, parent_asins, k=5):

    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-01-reviews",
        prefetch=[
            Prefetch(
                query=query_embedding,
                filter=Filter(
                    must=[
                        FieldCondition(
                            key="parent_asin",
                            match=MatchAny(
                                any=parent_asins
                            )
                        )
                    ]
                ),
                limit=20
            ),
        ],
        query=FusionQuery(fusion="rrf"),
        limit=k
    )

    return results

In [112]:
res = retrieve_prefiltered_reviews_data('bad quality reviews',['B08912RRG5'])

In [113]:
res.points

[ScoredPoint(id=3141, version=34, score=0.5, payload={'text': 'Bad product Poor quality', 'parent_asin': 'B08912RRG5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=672, version=9, score=0.33333334, payload={'text': 'good product good quality', 'parent_asin': 'B08912RRG5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=3567, version=38, score=0.25, payload={'text': 'Good quality Fit perfect', 'parent_asin': 'B08912RRG5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=4701, version=50, score=0.2, payload={'text': 'Good quality Good quality product', 'parent_asin': 'B08912RRG5'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=4771, version=50, score=0.16666667, payload={'text': 'The quality and the price Amazing', 'parent_asin': 'B08912RRG5'}, vector=None, shard_key=None, order_value=None)]